version: '3.8'

services:
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_SSL_KEYSTORE_LOCATION: /path/to/keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: your_keystore_password
      KAFKA_SSL_TRUSTSTORE_LOCATION: /path/to/truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: your_truststore_password
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  producer:
    build: ./producer
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_SSL_KEYSTORE_LOCATION: /path/to/keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: your_keystore_password
      KAFKA_SSL_TRUSTSTORE_LOCATION: /path/to/truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: your_truststore_password

  consumer:
    build: ./consumer
    depends_on:
      - kafka
      - db
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: rdp_results
      KAFKA_SSL_KEYSTORE_LOCATION: /path/to/keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: your_keystore_password
      KAFKA_SSL_TRUSTSTORE_LOCATION: /path/to/truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: your_truststore_password

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rdp_results
      POSTGRES_SSLMODE: require
      POSTGRES_SSLROOTCERT: /path/to/root.crt
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
