global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'producer'
    static_configs:
      - targets: ['producer:8080']

  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:8080']

  - job_name: 'db'
    static_configs:
      - targets: ['db:5432']
